theme: null

plugins:
  - jekyll-feed

markdown: kramdown

permalink: /:year-:month-:day-:title.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:year-:month-:day-:title.html
