# Базовая тема (можно закомментировать, если хотите полностью контролировать через _layouts)
remote_theme: pages-themes/minima@v0.2.0

# Плагины Jekyll
plugins:
  - jekyll-feed

# Markdown‑парсер
markdown: kramdown

# Общий формат URL для всех постов
permalink: /:year-:month-:day-:title.html

# Значения по умолчанию для _posts
defaults:
  -
    scope:
      path: ""     # весь сайт
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year-:month-:day-:title.html"
