# ════════════════════════════════════════════════════════════
# Отключаем любую внешнюю тему — полностью контролируем через _layouts
theme: null

# Плагины Jekyll (jenkins-pages автоматически поддерживает эти)
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Парсер Markdown
markdown: kramdown

# Формат ссылок для всех постов (корневая папка)
permalink: /:year-:month-:day-:title.html

# Значения по умолчанию для всего, что лежит в _posts/
defaults:
  -
    scope:
      path: ""       # весь сайт
      type: "posts"  # только файлы в _posts/
    values:
      layout: post
      permalink: /:year-:month-:day-:title.html
# ════════════════════════════════════════════════════════════
