# ════════════════════════════════════════════════════════════
# Подключаем удалённую тему minima
remote_theme: pages-themes/minima@v0.2.0

# Отключаем встроенную тему, чтобы не было конфликта
theme: null

# Плагины, которые нам нужны
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Парсер Markdown
markdown: kramdown

# ЧПУ для постов
permalink: /:year-:month-:day-:title.html

# По-умолчанию для файлов из _posts используем layout "post"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:year-:month-:day-:title.html
