# Отключаем внешнюю тему, полностью контролируем через _layouts
theme: null

# Плагины (GitHub Pages уже предустановлены)
plugins:
  - jekyll-feed

# Markdown‑парсер
markdown: kramdown

# Фиксируем URL для всех постов
permalink: /:year-:month-:day-:title.html

# Значения по умолчанию для файлов из _posts
defaults:
  -
    scope:
      path: ""       # весь сайт
      type: "posts"
    values:
      layout: post
