# .github/workflows/pages.yml
name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Забираем код
      - uses: actions/checkout@v3

      # 2. Устанавливаем Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # 4. Собираем сайт
      - name: Build the site
        run: bundle exec jekyll build --destination _site

      # 5. Загружаем артефакт для деплоя
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 6. Деплой
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
