# .github/workflows/pages.yml
name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:   # можно запускать вручную из UI

permissions:
  contents: read       # нужно читать репозиторий
  pages: write         # нужно право заливать Pages
  id-token: write      # для GitHub Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'      # любая актуальная 3.x
          bundler-cache: true      # кэшируем vendor/bundle автоматически

      - name: Build site with Jekyll
        # bundler-cache: true автоматически делает `bundle install`
        run: |
          bundle exec jekyll build --destination ./_site

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v2
