name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # укажи свою ветку, если у тебя не main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # можешь указать свою версию

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      - name: Debug _site content and links
        run: |
          echo "Listing all files in _site:"
          find _site
          echo "Checking for symbolic links in _site:"
          find _site -type l
          echo "Checking for hard links (files with link count > 1) in _site:"
          find _site -type f -links +1
          echo "Disk usage of _site directory:"
          du -sh _site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
